### ISSUE TITLE
Update `aes` version

### ISSUE THREAD

**Issue by xpepermint** [str4d/fpe#26]
This crate depends on `aes = "^0.7"` and thus doesn't work with the latest `aes = "0.8.1"`.

**Comment by daira** [comment]
In https://github.com/zcash/librustzcash/issues/757 I recommend the following for `fpe`, to help to reduce duplicate crate dependencies in Zcash:
- depend on cipher 0.4 [instead of cipher 0.3](https://github.com/str4d/fpe/blob/92e5193ea61cc90986c7ba4e686579cb07841027/Cargo.toml#L16)
- depend on aes 0.8 [instead of aes 0.7](https://github.com/str4d/fpe/blob/92e5193ea61cc90986c7ba4e686579cb07841027/Cargo.toml#L24)
- replace the [dependency on block-modes 0.8](https://github.com/str4d/fpe/blob/92e5193ea61cc90986c7ba4e686579cb07841027/Cargo.toml#L15), [which says](https://crates.io/crates/block-modes): "This crate is deprecated. Use crates from https://github.com/RustCrypto/block-modes instead." Based on [this](https://github.com/str4d/fpe/blob/92e5193ea61cc90986c7ba4e686579cb07841027/src/ff1.rs#L6) I think it probably wants [cbc 0.1](https://github.com/RustCrypto/block-modes/blob/master/cbc/Cargo.toml) (which depends on cipher 0.4.2 and aes 0.8).

**Comment by rohitjoshi** [comment]
Any update on this?
