### ISSUE TITLE
Failed to convert to BigUInt from encrypted value

### ISSUE THREAD

**Issue by rohitjoshi** [str4d/fpe#46]
I am able to encrypt and decrypt the value fine but the encrypted value is not format-preserving. 

When I try to convert the encrypted value to BigUInt using the below code, it returns None.
`let num_enc = BigUint::parse_bytes(&ns_encrypted.to_bytes_le(),10).unwrap();`

If I use `let num_enc_1 = BigUint::from_bytes_le(&ns_encrypted.to_bytes_le());`, it returns `692477047269896342546` which is not length preserving. 

```
#[test]
    fn fpe_ff1_test() {
        let bytes = b"123456789";
        let ns =  BinaryNumeralString::from_bytes_le(bytes);
        let num = BigUint::parse_bytes(&ns.to_bytes_le(),10).unwrap();
        println!("num:{:?}, ns_to_le:{:?}", num, ns.to_bytes_le());


        let fpe_ff = FF1::<Aes256>::new(&[0; 32], 2).unwrap();
        let ns_encrypted = fpe_ff.encrypt(&[], &ns).unwrap();
        println!("ns_encrypted_to_le:{:?}", ns_encrypted.to_bytes_le());

        //UNCOMMENT to reproduce the error
        //let num_enc = BigUint::parse_bytes(&ns_encrypted.to_bytes_le(),10).unwrap();
        //println!("num_enc_1:{}", num_enc);

        let ns_decrypted = fpe_ff.decrypt(&[], &ns_encrypted).unwrap();
        println!("ns_decrypted_to_le:{:?}", ns_decrypted.to_bytes_le());
        assert_eq!(bytes.to_vec(), ns_decrypted.to_bytes_le());

        let num_decrypted = BigUint::parse_bytes(&ns_decrypted.to_bytes_le(),10).unwrap();
        println!("num_decrypted:{}", num_decrypted);

        assert_eq!(num, num_decrypted);

      
        let num_enc_1 = BigUint::from_bytes_le(&ns_encrypted.to_bytes_le());
        println!("num_enc_1:{}", num_enc_1);
        let num_decrypted_1= BigUint::from_bytes_le(&ns_decrypted.to_bytes_le());
        println!("num_decrypted_1:{}", num_decrypted_1);
    }
```

**Comment by rohitjoshi** [comment]
I also tried replacing `BinaryNumeralString` with `FlexibleNumeralString` but the length is not preserved for certain values. 
eg. Input num: `859682506` with length `9` but the encrypted value is `23296462` which is length `8`. 
I did not see this issue in the `release-0.5.1`.

**Comment by str4d** [comment]
> ```
> let bytes = b"123456789";
> let ns =  7(bytes);
> let num = BigUint::parse_bytes(&ns.to_bytes_le(),10).unwrap();
> println!("num:{:?}, ns_to_le:{:?}", num, ns.to_bytes_le());
>
> let fpe_ff = FF1::<Aes256>::new(&[0; 32], 2).unwrap();
> let ns_encrypted = fpe_ff.encrypt(&[], &ns).unwrap();
> println!("ns_encrypted_to_le:{:?}", ns_encrypted.to_bytes_le());
>
> //UNCOMMENT to reproduce the error
> //let num_enc = BigUint::parse_bytes(&ns_encrypted.to_bytes_le(),10).unwrap();
> //println!("num_enc_1:{}", num_enc);
> ```

This will never work.

The problem is that the code is using `BinaryNumeralString`, which preserves a radix 2 format, and then is attempting to parse the resulting bytes as ASCII-encoded decimals, which requires preserving a radix 10 format.

Making the types explicit:
- `b"123456789"` is decimal integers encoded as UTF-8 bytes (which happens to coincide with ASCII encoding).
- `BigUint::parse_bytes` expects bytes containing ASCII-encoded integers (because the radix is set to 10).
- `BinaryNumeralString::from_bytes_le` parses bytes into a "numeral string" consisting of the bits in those bytes, i.e. the bits in the ASCII encoding of decimal integers.
- `ns_encrypted` will therefore also be a "numeral string" consisting of the same number of bits (because the preserved format is "binary numeral string of length N"), with random-looking bit values (because it's encrypted).
- `ns_encrypted.to_bytes_le()` will therefore output random-looking (encrypted) bytes, each in the range `0..=255`, which includes values outside the range of ASCII-encoded integers, causing the error.

> I also tried replacing `BinaryNumeralString` with `FlexibleNumeralString`

This is the correct thing to do. If you need the encrypted values to look like the string encoding of decimal integers, then you need to use radix 10 numeral strings to ensure the encrypted numerals are only in the range `0..=9`.

> but the length is not preserved for certain values. eg. Input num: `859682506` with length `9` but the encrypted value is `23296462` which is length `8`.

Check the output of `FF1::encrypt` before converting to a `BigUint`. My guess is that those values encrypt to a radix 10 numeral string that starts with one or more zeros, which `BigUint` won't preserve in its `Display` impl. In your example, I expect that `859682506` is being encrypted to `023296462`. If you want to use `BigUint`, you should zero-extend the values to the required length before encrypting / decrypting.

**Comment by rohitjoshi** [comment]
That worked. Thanks.
